//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Input {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeTests.Resources.Input", typeof(Input).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Example1.
        /// </summary>
        public static string D00_E1 {
            get {
                return ResourceManager.GetString("D00_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Example2.
        /// </summary>
        public static string D00_E2 {
            get {
                return ResourceManager.GetString("D00_E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Puzzle.
        /// </summary>
        public static string D00_Puzzle {
            get {
                return ResourceManager.GetString("D00_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1384
        ///1396
        ///1072
        ///1903
        ///1387
        ///1763
        ///1600
        ///1862
        ///1992
        ///1585
        ///1909
        ///1352
        ///1288
        ///1910
        ///1070
        ///1421
        ///1802
        ///1669
        ///1059
        ///1235
        ///1854
        ///1722
        ///1275
        ///198
        ///1476
        ///1588
        ///1708
        ///1217
        ///1596
        ///1355
        ///1566
        ///1973
        ///1335
        ///1480
        ///1115
        ///1272
        ///1998
        ///1821
        ///2007
        ///1721
        ///1885
        ///1420
        ///1412
        ///1487
        ///1941
        ///1835
        ///1558
        ///1061
        ///1582
        ///1940
        ///1942
        ///1210
        ///1350
        ///1175
        ///1047
        ///1456
        ///1548
        ///1110
        ///1510
        ///1995
        ///1644
        ///1968
        ///1297
        ///1198
        ///1471
        ///1360
        ///1363
        ///1528
        ///1393
        ///1365
        ///1837
        ///1886
        ///2001
        ///1161
        ///1349
        ///1787
        ///988
        ///1331
        ///1960
        ///1607
        ///1324
        ///97
        ///1986
        ///1955
        ///1773
        ///1443
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D01_Puzzle {
            get {
                return ResourceManager.GetString("D01_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14-15 v: vdvvvvvsvvvvvfpv
        ///3-11 k: kkqkkfkkvkgfknkx
        ///6-10 j: jjjjjjjjjj
        ///5-10 s: nskdmzwrmpmhsrzts
        ///13-15 v: vvvvvvkvvvvjzvv
        ///11-13 h: hhhhhbhhhhdhhh
        ///14-15 r: rrrrrrrrzrrrrrtl
        ///2-9 c: llhctjgbz
        ///13-15 s: ssssxssssssssjs
        ///6-8 c: lccccqcc
        ///8-9 n: nnnnnmnch
        ///4-5 n: jnnnmmpxngbrknzb
        ///4-7 n: knlnqnnndnn
        ///13-18 g: ggggggggnggggggggggp
        ///5-6 m: mmmmgm
        ///5-10 l: lvlllglllpll
        ///7-12 z: pszgzqzzzzkw
        ///1-2 j: pjjqw
        ///15-16 n: nnnnnnnnnnnnnnpn
        ///8-14 z: mzzzjzzzzhzzzztznzz
        ///5-19 q: rnsdfgkqlqjdvrmtsqqh
        ///1-5 f: ffffff
        ///4-5 h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D02_Puzzle {
            get {
                return ResourceManager.GetString("D02_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...#..............#.#....#..#..
        ///...#..#..#..............#..#...
        ///....#.#.......#............#...
        ///..##.....##.........#........##
        ///...#...........#...##.#...#.##.
        ///..#.#...#....#.....#........#..
        ///....##.###.....#..#.......#....
        ///.#..##...#.....#......#..#.....
        ///............##.#...#.#.....#.#.
        ///..........#....#....#.#...#...#
        ///..##....#.#.#......#.........#.
        ///#.#.........#..............##..
        ///....##.##......................
        ///....##..#...........#..........
        ///..#..#.#........##....#......#.
        ///..............#.. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D03_Puzzle {
            get {
                return ResourceManager.GetString("D03_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iyr:2015
        ///hgt:59cm byr:2029 cid:219 pid:9381688753 eyr:1992 hcl:#b6652a
        ///ecl:#7a0fa6
        ///
        ///ecl:blu iyr:2018 pid:943614755 cid:335
        ///byr:1968
        ///eyr:2026
        ///
        ///pid:067285985 hcl:#ceb3a1 cid:281
        ///ecl:#07219a eyr:1944
        ///iyr:2025
        ///byr:2029 hgt:64cm
        ///
        ///hgt:185cm
        ///ecl:gry cid:222
        ///iyr:2016
        ///hcl:#866857 byr:1970 pid:269105457 eyr:2026
        ///
        ///pid:260043570 hcl:#b6652a cid:275 byr:1990 ecl:brn
        ///hgt:163cm iyr:2012
        ///
        ///hgt:181cm pid:604983466
        ///iyr:1930 eyr:2039 byr:1950 ecl:#906548 hcl:#b6652a
        ///
        ///iyr:2025 eyr:1956 hcl:z pid:#1c42cc  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D04_Puzzle {
            get {
                return ResourceManager.GetString("D04_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBBBFFFLRL
        ///BFFBBBBLRL
        ///FBFFFBBRRR
        ///FBFBBFFLRL
        ///FFFBFBBRLR
        ///FBFBBBFRLL
        ///BFBFFBFRLR
        ///BFBFFFBRRL
        ///BFBBFFBRLR
        ///FBBFBBBRLL
        ///FFFBBFFRRR
        ///FFBBBFBRLR
        ///BBFFBFBLLL
        ///BBFFBBFRRR
        ///BBFBFFBLLR
        ///FFFBBBFLRR
        ///BBFBBFFRLR
        ///BBFFFBFRLL
        ///FBFFBFBLLR
        ///FBBFFFBRLR
        ///BFFFFBFLRR
        ///BBFFBBBLRL
        ///FBFBBFFRRL
        ///BBFFFFFLRR
        ///BFBBBFBRRL
        ///BBFFBBBRLR
        ///FFBFBFBRLL
        ///BFBFFBFLLR
        ///FBBFBBFRLR
        ///BBFFFBBRLR
        ///BBFFBBFLLR
        ///FFBBBBBRRL
        ///BFFFBFBRRL
        ///FFBFFFBRRL
        ///FBBBBFBLLL
        ///FBBFFBFLRR
        ///BBFFFFBRRL
        ///FFBFBFBLRR
        ///FFBBFBBLLR
        ///BFBFBBFRLL
        ///BBFFFBFLLL
        ///FBBBBFFRRR
        ///BBFBFFFR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D05_Puzzle {
            get {
                return ResourceManager.GetString("D05_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kimczeyaqwbs
        ///pwmsf
        ///wgmfus
        ///lofjwnms
        ///rwsum
        ///
        ///hndgqzkvtyxoifsemrpjaul
        ///brfzpmgesjihuvxqyontdaklw
        ///fakydqpuriljosvhmxtezng
        ///qerstgynxplkhmoiuvzdjaf
        ///
        ///pxygsaovwnuqthke
        ///ygqnepvuxhswtao
        ///
        ///o
        ///o
        ///
        ///uogzqatjwyihskpdlen
        ///wkidlyahtzougjpnseq
        ///ylputjwoaizqdekgnsh
        ///
        ///diejltaxoqgfsckymvpwzu
        ///vtypfnsojcqilbuazg
        ///
        ///lkvqinopx
        ///gptazfonbq
        ///oqahpnz
        ///qpowmnb
        ///neqodhjp
        ///
        ///hzqgiaksvouycjpwet
        ///izakeohctsuypgjvwq
        ///eojhzasvqitygcpwuk
        ///jkstuviacphgwezyoq
        ///
        ///voksmqfalh
        ///fywojdbrvpax
        ///cefovustagzn
        ///
        ///wdkcuiyegrl
        ///zmnixqbeyw
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D06_Puzzle {
            get {
                return ResourceManager.GetString("D06_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vibrant bronze bags contain 3 dim olive bags.
        ///shiny teal bags contain 1 posh green bag, 5 pale indigo bags, 1 mirrored purple bag.
        ///striped aqua bags contain 5 bright orange bags.
        ///clear chartreuse bags contain 3 dotted black bags, 2 wavy olive bags.
        ///light lime bags contain 1 posh silver bag, 5 clear orange bags, 2 light olive bags, 3 dull maroon bags.
        ///light olive bags contain 4 striped turquoise bags.
        ///shiny purple bags contain 2 posh silver bags, 3 striped silver bags, 5 shiny beige bags, 2 plaid chart [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D07_Puzzle {
            get {
                return ResourceManager.GetString("D07_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acc +7
        ///acc +23
        ///acc +41
        ///jmp +173
        ///acc -17
        ///acc +42
        ///acc +31
        ///jmp +349
        ///jmp +1
        ///jmp +252
        ///nop +574
        ///jmp +298
        ///acc +45
        ///acc +7
        ///jmp +338
        ///nop +5
        ///nop +528
        ///jmp +547
        ///jmp +313
        ///jmp +387
        ///acc +43
        ///acc +48
        ///acc +38
        ///jmp +45
        ///jmp +438
        ///acc +15
        ///acc +21
        ///acc +25
        ///acc +25
        ///jmp +168
        ///jmp -5
        ///acc +49
        ///acc +43
        ///jmp +99
        ///acc -8
        ///acc +16
        ///acc -7
        ///jmp +513
        ///jmp +484
        ///jmp +270
        ///nop +422
        ///acc -4
        ///nop +242
        ///jmp +1
        ///jmp +11
        ///nop +122
        ///nop +263
        ///acc +2
        ///jmp +474
        ///jmp +501
        ///nop +38
        ///acc -7
        ///acc +0
        ///nop +85
        ///jmp +496
        ///acc +11 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D08_Puzzle {
            get {
                return ResourceManager.GetString("D08_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23
        ///3
        ///36
        ///14
        ///50
        ///8
        ///2
        ///44
        ///30
        ///37
        ///20
        ///5
        ///34
        ///41
        ///31
        ///39
        ///28
        ///24
        ///49
        ///42
        ///22
        ///4
        ///45
        ///46
        ///32
        ///6
        ///35
        ///7
        ///26
        ///15
        ///21
        ///8
        ///9
        ///12
        ///25
        ///10
        ///11
        ///13
        ///14
        ///16
        ///17
        ///57
        ///18
        ///64
        ///19
        ///20
        ///22
        ///33
        ///27
        ///23
        ///24
        ///28
        ///29
        ///30
        ///38
        ///31
        ///37
        ///35
        ///21
        ///26
        ///44
        ///25
        ///32
        ///34
        ///36
        ///69
        ///40
        ///51
        ///39
        ///43
        ///41
        ///45
        ///46
        ///63
        ///49
        ///54
        ///47
        ///66
        ///64
        ///55
        ///52
        ///65
        ///53
        ///57
        ///59
        ///83
        ///61
        ///92
        ///70
        ///97
        ///79
        ///80
        ///82
        ///84
        ///86
        ///87
        ///91
        ///93
        ///96
        ///101
        ///99
        ///148
        ///105
        ///107
        ///109
        ///110
        ///112
        ///114
        ///116
        ///166
        ///204
        ///191
        ///196
        ///149
        ///159
        ///161
        ///198
        ///240
        ///170
        ///173
        ///178
        ///190
        ///219
        ///314
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D09_Puzzle {
            get {
                return ResourceManager.GetString("D09_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26
        ///97
        ///31
        ///7
        ///2
        ///10
        ///46
        ///38
        ///112
        ///54
        ///30
        ///93
        ///18
        ///111
        ///29
        ///75
        ///139
        ///23
        ///132
        ///85
        ///78
        ///99
        ///8
        ///113
        ///87
        ///57
        ///133
        ///41
        ///104
        ///98
        ///58
        ///90
        ///13
        ///91
        ///20
        ///68
        ///103
        ///127
        ///105
        ///114
        ///138
        ///126
        ///67
        ///32
        ///145
        ///115
        ///16
        ///141
        ///1
        ///73
        ///45
        ///119
        ///51
        ///40
        ///35
        ///150
        ///118
        ///53
        ///80
        ///79
        ///65
        ///135
        ///74
        ///47
        ///128
        ///64
        ///17
        ///4
        ///84
        ///83
        ///147
        ///142
        ///146
        ///9
        ///125
        ///94
        ///140
        ///131
        ///134
        ///92
        ///66
        ///122
        ///19
        ///86
        ///50
        ///52
        ///108
        ///100
        ///71
        ///61
        ///44
        ///39
        ///3
        ///72.
        /// </summary>
        public static string D10_Puzzle {
            get {
                return ResourceManager.GetString("D10_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLLLLLLLLL.LLLL.LLLLLLL.LLLLL.LLLLLLLLLLLLLLLLLLLLLL.LL.LLLLLLLLLLL.LLLLLL.LL.LLLL.LLLLLL.LLLLLLL
        ///LL.LLLLLLL.LLLLLLLLLLLL.LLLLL.LLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLLL.LLLLLLLLL.LL.LLLL.LLLLLL.LLLLLLL
        ///LLLLLL.LLLLLLLLLLLLLLLL.LLL.L.LLLLLLLL.LLLL.LLLL.LLLLLL.LLLLLLLLLLLLLLLLLLLLLLLLLL.LLLL.L.LLLLLLL
        ///LLLLLLLLLL.LLLL.LLLLLLLLLLLLL.LLLLLLLL.LLLLLLLLL.LLLLLLLLLLLLLLL.LLLLLLLLLLLLLLLLL.LLLLLLLLLLLLLL
        ///LLLLLLLLLLLLLLL.LLLLLLL.LLLLL.LLLLLL.L.LLLLLLLLL.LLLLLL.LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL.LLLLLLL
        ///LLLLLLLLLL.LLLLLL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D11_Puzzle {
            get {
                return ResourceManager.GetString("D11_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W1
        ///L90
        ///F26
        ///S3
        ///W2
        ///N5
        ///L180
        ///S4
        ///F41
        ///W1
        ///F48
        ///W3
        ///F44
        ///F63
        ///W5
        ///N3
        ///E5
        ///F7
        ///R180
        ///W1
        ///N3
        ///W3
        ///R180
        ///F38
        ///N1
        ///E3
        ///L90
        ///F49
        ///S5
        ///F11
        ///E1
        ///R90
        ///W3
        ///N4
        ///E3
        ///R180
        ///W5
        ///F93
        ///S1
        ///F67
        ///L180
        ///W3
        ///S5
        ///N3
        ///L180
        ///E1
        ///N2
        ///F90
        ///S3
        ///W3
        ///N3
        ///E1
        ///F77
        ///W3
        ///N3
        ///L180
        ///E2
        ///F25
        ///N1
        ///W1
        ///S1
        ///E5
        ///S4
        ///R180
        ///W1
        ///F13
        ///L90
        ///W4
        ///S5
        ///F13
        ///N2
        ///R90
        ///F89
        ///R90
        ///W3
        ///L90
        ///W5
        ///N5
        ///E4
        ///S4
        ///F26
        ///N1
        ///R270
        ///N5
        ///E5
        ///L180
        ///R180
        ///W4
        ///R90
        ///W5
        ///F49
        ///S2
        ///F53
        ///W5
        ///L180
        ///F54
        ///L90
        ///N3
        ///F3
        ///W5
        ///R180
        ///S4
        ///L90
        ///F49
        ///W4
        ///S5
        ///F73
        ///L270
        ///W1
        ///S4
        ///F46
        ///S4
        ///W2        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D12_Puzzle {
            get {
                return ResourceManager.GetString("D12_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000417
        ///23,x,x,x,x,x,x,x,x,x,x,x,x,41,x,x,x,37,x,x,x,x,x,479,x,x,x,x,x,x,x,x,x,x,x,x,13,x,x,x,17,x,x,x,x,x,x,x,x,x,x,x,29,x,373,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,19.
        /// </summary>
        public static string D13_Puzzle {
            get {
                return ResourceManager.GetString("D13_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mask = X00X0X0110010001010X0000000010001111
        ///mem[36604] = 2508973
        ///mem[14290] = 80919
        ///mem[6865] = 15237
        ///mem[45983] = 393572789
        ///mask = X101001X0XX00111000110X0010000110110
        ///mem[300] = 253232
        ///mem[5315] = 56368
        ///mem[64425] = 18227
        ///mem[20919] = 4682858
        ///mem[39194] = 54595
        ///mem[32891] = 32798017
        ///mask = X1X00101XX00000111X11X0000100000010X
        ///mem[22572] = 2370
        ///mem[61212] = 13199
        ///mem[15537] = 15245
        ///mem[29581] = 9182
        ///mem[38437] = 15367
        ///mem[62023] = 300695
        ///mem[63267] = 7104850
        ///mask = 0X0000X0X000001X00011 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D14_Puzzle {
            get {
                return ResourceManager.GetString("D14_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,3,1,6,7,5.
        /// </summary>
        public static string D15_Puzzle {
            get {
                return ResourceManager.GetString("D15_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departure location: 31-538 or 546-960
        ///departure station: 39-660 or 673-960
        ///departure platform: 35-731 or 745-968
        ///departure track: 43-179 or 185-953
        ///departure date: 29-250 or 263-949
        ///departure time: 43-903 or 928-954
        ///arrival location: 46-372 or 384-968
        ///arrival station: 36-215 or 225-950
        ///arrival platform: 25-631 or 655-950
        ///arrival track: 26-768 or 781-962
        ///class: 29-462 or 478-974
        ///duration: 34-441 or 455-963
        ///price: 39-683 or 693-956
        ///route: 36-342 or 348-971
        ///row: 37-501 or 520-963
        ///seat: 46-356 or [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D16_Puzzle {
            get {
                return ResourceManager.GetString("D16_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #......#
        ///##.#..#.
        ///#.#.###.
        ///.##.....
        ///.##.#...
        ///##.#....
        ///#####.#.
        ///##.#.###.
        /// </summary>
        public static string D17_Puzzle {
            get {
                return ResourceManager.GetString("D17_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day18_Puzzle.
        /// </summary>
        public static string D18_Puzzle {
            get {
                return ResourceManager.GetString("D18_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day19_Puzzle.
        /// </summary>
        public static string D19_Puzzle {
            get {
                return ResourceManager.GetString("D19_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day20_Puzzle.
        /// </summary>
        public static string D20_Puzzle {
            get {
                return ResourceManager.GetString("D20_Puzzle", resourceCulture);
            }
        }
    }
}
