//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Input {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeTests.Resources.Input", typeof(Input).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Example1.
        /// </summary>
        public static string D00_E1 {
            get {
                return ResourceManager.GetString("D00_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Example2.
        /// </summary>
        public static string D00_E2 {
            get {
                return ResourceManager.GetString("D00_E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Puzzle.
        /// </summary>
        public static string D00_Puzzle {
            get {
                return ResourceManager.GetString("D00_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1384
        ///1396
        ///1072
        ///1903
        ///1387
        ///1763
        ///1600
        ///1862
        ///1992
        ///1585
        ///1909
        ///1352
        ///1288
        ///1910
        ///1070
        ///1421
        ///1802
        ///1669
        ///1059
        ///1235
        ///1854
        ///1722
        ///1275
        ///198
        ///1476
        ///1588
        ///1708
        ///1217
        ///1596
        ///1355
        ///1566
        ///1973
        ///1335
        ///1480
        ///1115
        ///1272
        ///1998
        ///1821
        ///2007
        ///1721
        ///1885
        ///1420
        ///1412
        ///1487
        ///1941
        ///1835
        ///1558
        ///1061
        ///1582
        ///1940
        ///1942
        ///1210
        ///1350
        ///1175
        ///1047
        ///1456
        ///1548
        ///1110
        ///1510
        ///1995
        ///1644
        ///1968
        ///1297
        ///1198
        ///1471
        ///1360
        ///1363
        ///1528
        ///1393
        ///1365
        ///1837
        ///1886
        ///2001
        ///1161
        ///1349
        ///1787
        ///988
        ///1331
        ///1960
        ///1607
        ///1324
        ///97
        ///1986
        ///1955
        ///1773
        ///1443
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D01_Puzzle {
            get {
                return ResourceManager.GetString("D01_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14-15 v: vdvvvvvsvvvvvfpv
        ///3-11 k: kkqkkfkkvkgfknkx
        ///6-10 j: jjjjjjjjjj
        ///5-10 s: nskdmzwrmpmhsrzts
        ///13-15 v: vvvvvvkvvvvjzvv
        ///11-13 h: hhhhhbhhhhdhhh
        ///14-15 r: rrrrrrrrzrrrrrtl
        ///2-9 c: llhctjgbz
        ///13-15 s: ssssxssssssssjs
        ///6-8 c: lccccqcc
        ///8-9 n: nnnnnmnch
        ///4-5 n: jnnnmmpxngbrknzb
        ///4-7 n: knlnqnnndnn
        ///13-18 g: ggggggggnggggggggggp
        ///5-6 m: mmmmgm
        ///5-10 l: lvlllglllpll
        ///7-12 z: pszgzqzzzzkw
        ///1-2 j: pjjqw
        ///15-16 n: nnnnnnnnnnnnnnpn
        ///8-14 z: mzzzjzzzzhzzzztznzz
        ///5-19 q: rnsdfgkqlqjdvrmtsqqh
        ///1-5 f: ffffff
        ///4-5 h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D02_Puzzle {
            get {
                return ResourceManager.GetString("D02_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...#..............#.#....#..#..
        ///...#..#..#..............#..#...
        ///....#.#.......#............#...
        ///..##.....##.........#........##
        ///...#...........#...##.#...#.##.
        ///..#.#...#....#.....#........#..
        ///....##.###.....#..#.......#....
        ///.#..##...#.....#......#..#.....
        ///............##.#...#.#.....#.#.
        ///..........#....#....#.#...#...#
        ///..##....#.#.#......#.........#.
        ///#.#.........#..............##..
        ///....##.##......................
        ///....##..#...........#..........
        ///..#..#.#........##....#......#.
        ///..............#.. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D03_Puzzle {
            get {
                return ResourceManager.GetString("D03_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iyr:2015
        ///hgt:59cm byr:2029 cid:219 pid:9381688753 eyr:1992 hcl:#b6652a
        ///ecl:#7a0fa6
        ///
        ///ecl:blu iyr:2018 pid:943614755 cid:335
        ///byr:1968
        ///eyr:2026
        ///
        ///pid:067285985 hcl:#ceb3a1 cid:281
        ///ecl:#07219a eyr:1944
        ///iyr:2025
        ///byr:2029 hgt:64cm
        ///
        ///hgt:185cm
        ///ecl:gry cid:222
        ///iyr:2016
        ///hcl:#866857 byr:1970 pid:269105457 eyr:2026
        ///
        ///pid:260043570 hcl:#b6652a cid:275 byr:1990 ecl:brn
        ///hgt:163cm iyr:2012
        ///
        ///hgt:181cm pid:604983466
        ///iyr:1930 eyr:2039 byr:1950 ecl:#906548 hcl:#b6652a
        ///
        ///iyr:2025 eyr:1956 hcl:z pid:#1c42cc  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D04_Puzzle {
            get {
                return ResourceManager.GetString("D04_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBBBFFFLRL
        ///BFFBBBBLRL
        ///FBFFFBBRRR
        ///FBFBBFFLRL
        ///FFFBFBBRLR
        ///FBFBBBFRLL
        ///BFBFFBFRLR
        ///BFBFFFBRRL
        ///BFBBFFBRLR
        ///FBBFBBBRLL
        ///FFFBBFFRRR
        ///FFBBBFBRLR
        ///BBFFBFBLLL
        ///BBFFBBFRRR
        ///BBFBFFBLLR
        ///FFFBBBFLRR
        ///BBFBBFFRLR
        ///BBFFFBFRLL
        ///FBFFBFBLLR
        ///FBBFFFBRLR
        ///BFFFFBFLRR
        ///BBFFBBBLRL
        ///FBFBBFFRRL
        ///BBFFFFFLRR
        ///BFBBBFBRRL
        ///BBFFBBBRLR
        ///FFBFBFBRLL
        ///BFBFFBFLLR
        ///FBBFBBFRLR
        ///BBFFFBBRLR
        ///BBFFBBFLLR
        ///FFBBBBBRRL
        ///BFFFBFBRRL
        ///FFBFFFBRRL
        ///FBBBBFBLLL
        ///FBBFFBFLRR
        ///BBFFFFBRRL
        ///FFBFBFBLRR
        ///FFBBFBBLLR
        ///BFBFBBFRLL
        ///BBFFFBFLLL
        ///FBBBBFFRRR
        ///BBFBFFFR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D05_Puzzle {
            get {
                return ResourceManager.GetString("D05_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kimczeyaqwbs
        ///pwmsf
        ///wgmfus
        ///lofjwnms
        ///rwsum
        ///
        ///hndgqzkvtyxoifsemrpjaul
        ///brfzpmgesjihuvxqyontdaklw
        ///fakydqpuriljosvhmxtezng
        ///qerstgynxplkhmoiuvzdjaf
        ///
        ///pxygsaovwnuqthke
        ///ygqnepvuxhswtao
        ///
        ///o
        ///o
        ///
        ///uogzqatjwyihskpdlen
        ///wkidlyahtzougjpnseq
        ///ylputjwoaizqdekgnsh
        ///
        ///diejltaxoqgfsckymvpwzu
        ///vtypfnsojcqilbuazg
        ///
        ///lkvqinopx
        ///gptazfonbq
        ///oqahpnz
        ///qpowmnb
        ///neqodhjp
        ///
        ///hzqgiaksvouycjpwet
        ///izakeohctsuypgjvwq
        ///eojhzasvqitygcpwuk
        ///jkstuviacphgwezyoq
        ///
        ///voksmqfalh
        ///fywojdbrvpax
        ///cefovustagzn
        ///
        ///wdkcuiyegrl
        ///zmnixqbeyw
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D06_Puzzle {
            get {
                return ResourceManager.GetString("D06_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vibrant bronze bags contain 3 dim olive bags.
        ///shiny teal bags contain 1 posh green bag, 5 pale indigo bags, 1 mirrored purple bag.
        ///striped aqua bags contain 5 bright orange bags.
        ///clear chartreuse bags contain 3 dotted black bags, 2 wavy olive bags.
        ///light lime bags contain 1 posh silver bag, 5 clear orange bags, 2 light olive bags, 3 dull maroon bags.
        ///light olive bags contain 4 striped turquoise bags.
        ///shiny purple bags contain 2 posh silver bags, 3 striped silver bags, 5 shiny beige bags, 2 plaid chart [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D07_Puzzle {
            get {
                return ResourceManager.GetString("D07_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acc +7
        ///acc +23
        ///acc +41
        ///jmp +173
        ///acc -17
        ///acc +42
        ///acc +31
        ///jmp +349
        ///jmp +1
        ///jmp +252
        ///nop +574
        ///jmp +298
        ///acc +45
        ///acc +7
        ///jmp +338
        ///nop +5
        ///nop +528
        ///jmp +547
        ///jmp +313
        ///jmp +387
        ///acc +43
        ///acc +48
        ///acc +38
        ///jmp +45
        ///jmp +438
        ///acc +15
        ///acc +21
        ///acc +25
        ///acc +25
        ///jmp +168
        ///jmp -5
        ///acc +49
        ///acc +43
        ///jmp +99
        ///acc -8
        ///acc +16
        ///acc -7
        ///jmp +513
        ///jmp +484
        ///jmp +270
        ///nop +422
        ///acc -4
        ///nop +242
        ///jmp +1
        ///jmp +11
        ///nop +122
        ///nop +263
        ///acc +2
        ///jmp +474
        ///jmp +501
        ///nop +38
        ///acc -7
        ///acc +0
        ///nop +85
        ///jmp +496
        ///acc +11 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D08_Puzzle {
            get {
                return ResourceManager.GetString("D08_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day09_Puzzle.
        /// </summary>
        public static string D09_Puzzle {
            get {
                return ResourceManager.GetString("D09_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day10_Puzzle.
        /// </summary>
        public static string D10_Puzzle {
            get {
                return ResourceManager.GetString("D10_Puzzle", resourceCulture);
            }
        }
    }
}
